### PR TITLE
Implement skeleton for basic player control

### PR DESCRIPTION
**Pull request by MaXeraph**
## Changes
- PlayerControls to call modifying scripts on each input
- MouseLook was based of GameJam2
- Movement, Shoot not fully implemented

### CODE REVIEW

**Comment by Sirkular** [comment]
Why separate look controls and movement controls? Is there a benefit to doing controls this way?

**Comment by MaXeraph** [comment]
> Why separate look controls and movement controls? Is there a benefit to doing controls this way?

Moved scripts over https://github.com/MaXeraph/Adrenarun/pull/3/commits/b4205f250ab6df9e9a66ab7e8e08917201ae188e

**Review by zhuandy42 — APPROVED** [review]
lgtm

**Review by Sirkular — CHANGES_REQUESTED** [review]
MouseLook.cs.meta is leftover file that should be removed.

**Review by Sirkular — APPROVED** [review]

**Pull request merged**
